server:
  port: 8001

spring:
  application:
    name: producer
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.116.134:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      enabled: true
      datasource:
        flow:
          nacos:
            server-addr: 162.14.116.134:8848
            namespace: 5ae48cf6-108f-4de1-aa6b-f4369cae9e3e
            data‐type: json
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        degrade:
          nacos:
            server-addr: 162.14.116.134:8848
            namespace: 5ae48cf6-108f-4de1-aa6b-f4369cae9e3e
            data‐type: json
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
        system:
          nacos:
            server-addr: 162.14.116.134:8848
            namespace: 5ae48cf6-108f-4de1-aa6b-f4369cae9e3e
            data‐type: json
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
        authority:
          nacos:
            server-addr: 162.14.116.134:8848
            namespace: 5ae48cf6-108f-4de1-aa6b-f4369cae9e3e
            data‐type: json
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
        param-flow:
          nacos:
            server-addr: 162.14.116.134:8848
            namespace: 5ae48cf6-108f-4de1-aa6b-f4369cae9e3e
            data‐type: json
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow

  datasource:
    url: jdbc:mysql://119.3.143.23:3306/test1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: test1
    password: test1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'